// Generated by packages/ade/scripts/gen-frame-script.ts from src/browser/frame-script.ts. Do not edit.
;(function frameGuard(win, bridge) {
  if (win.top === win) return
  const define = Object.defineProperty,
    uncurry = Function.prototype.bind.bind(Function.prototype.call)
  if (win.__ADE_FRAME__) return
  define(win, "__ADE_FRAME__", { value: !0 })
  try {
    const Base = win.Headers
    if (typeof Base === "function") {
      const test = uncurry(RegExp.prototype.test),
        tauriHeader = /^\s*tauri-/i,
        isTauri = (name) => typeof name === "string" && test(tauriHeader, name),
        refuse = () => {
          throw TypeError("ADE: Tauri IPC is not available in a frame")
        }

      class FrameHeaders extends Base {
        set(name, value) {
          if (isTauri(name)) refuse()
          return super.set(name, value)
        }
        append(name, value) {
          if (isTauri(name)) refuse()
          return super.append(name, value)
        }
      }
      Object.freeze(FrameHeaders.prototype)
      Object.freeze(FrameHeaders)
      define(win, "Headers", { value: FrameHeaders, writable: !1, configurable: !1 })
    }
  } catch {}
  try {
    if (win.chrome && win.chrome.webview) {
      const inert = Object.freeze({
        postMessage() {},
        addEventListener() {},
        removeEventListener() {},
      })
      define(win.chrome, "webview", { value: inert, writable: !1, configurable: !1 })
    }
  } catch {}
  if (win.parent !== win.top || win.name !== "ade-browser") return
  const location = win.location || {},
    scheme = String(location.protocol)
  if (!(scheme === "http:" || scheme === "https:" || scheme === "blob:" || String(location.href) === "about:srcdoc"))
    return
  const eventProto = win.MessageEvent.prototype,
    getData = uncurry(Object.getOwnPropertyDescriptor(eventProto, "data").get),
    getSource = uncurry(Object.getOwnPropertyDescriptor(eventProto, "source").get),
    listen = uncurry(win.EventTarget.prototype.addEventListener),
    parent = win.parent,
    postToParent = uncurry(parent.postMessage),
    portProto = win.MessagePort.prototype,
    portPost = uncurry(portProto.postMessage),
    portStart = uncurry(portProto.start),
    computed = uncurry(win.getComputedStyle),
    push = uncurry(Array.prototype.push),
    shift = uncurry(Array.prototype.shift),
    trustedGetter = Object.getOwnPropertyDescriptor(new win.Event("ade"), "isTrusted"),
    isTrustedOf = trustedGetter && trustedGetter.get ? uncurry(trustedGetter.get) : void 0,
    trusted = (event) => {
      try {
        return isTrustedOf ? isTrustedOf(event) === !0 : !1
      } catch {
        return !1
      }
    }
  define(win, "__NIKCLI_INSPECTOR_ACTIVE__", { value: !0, writable: !1, configurable: !1 })
  let secret,
    started = !1
  const queue = [],
    channel = new win.MessageChannel(),
    port = channel.port1,
    send = (message) => {
      if (secret === void 0) {
        push(queue, message)
        return
      }
      portPost(port, { type: "ade-browser:bridge", secret, message })
    },
    listenTrusted = (target, type, handler, options) =>
      listen(
        target,
        type,
        (event) => {
          if (trusted(event)) handler(event)
        },
        options,
      )
  listen(port, "message", (event) => {
    const data = getData(event)
    if (!data || typeof data !== "object") return
    if (data.type === "ade-browser:ping") {
      portPost(port, { type: "ade-browser:pong" })
      return
    }
    if (data.type !== "ade-browser:hello" || secret !== void 0 || typeof data.secret !== "string") return
    secret = data.secret
    while (queue.length) send(shift(queue))
    if (started) return
    started = !0
    bridge({
      __NIKCLI_INSPECTOR_ACTIVE__: !1,
      __ADE_LISTEN__: listenTrusted,
      parent: { postMessage: (message) => send(message) },
      getComputedStyle: (element, pseudo) => computed(win, element, pseudo),
      addEventListener: (type, handler, options) => {
        if (type !== "message") return listen(win, type, handler, options)
        return listen(
          win,
          "message",
          (event) => {
            if (getSource(event) !== parent) return
            handler({ data: getData(event), source: parent })
          },
          options,
        )
      },
    })
  })
  portStart(port)
  postToParent(parent, { type: "ade-browser:ask" }, "*", [channel.port2])
})(window, function (window) {
  ;(function () {
    if (window.__NIKCLI_INSPECTOR_ACTIVE__) return
    window.__NIKCLI_INSPECTOR_ACTIVE__ = true

    // Only real input selects, drags or hovers: a page's dispatchEvent does not.
    // ADE's frame script hands over a listener taken before the page could
    // replace addEventListener; elsewhere the event's own flag is checked.
    var listenInput =
      window.__ADE_LISTEN__ ||
      function (target, type, handler, options) {
        target.addEventListener(
          type,
          function (e) {
            if (e.isTrusted) handler(e)
          },
          options,
        )
      }

    // Modes: 'browse' (normal browsing) | 'edit' (unified select-to-link & drag-and-drop)
    var currentMode = "browse"
    var hoveredEl = null
    var draggedEl = null
    var isDragging = false
    var dropTargetEl = null
    var dropPosition = null // 'before' | 'after'

    // Capture console logs and errors
    var originalConsole = {
      log: console.log,
      warn: console.warn,
      error: console.error,
      info: console.info,
    }

    function serializeArg(arg) {
      try {
        if (arg instanceof Error) return arg.stack || arg.message
        if (typeof arg === "object") return JSON.stringify(arg)
        return String(arg)
      } catch (e) {
        return String(arg)
      }
    }

    function forwardConsole(level, args) {
      var msg = Array.prototype.slice.call(args).map(serializeArg).join(" ")
      window.parent.postMessage(
        {
          type: "visual-editor:console-log",
          log: {
            level: level,
            message: msg.slice(0, 1000),
            timestamp: Date.now(),
          },
        },
        "*",
      )
    }

    console.log = function () {
      forwardConsole("log", arguments)
      originalConsole.log.apply(console, arguments)
    }
    console.warn = function () {
      forwardConsole("warn", arguments)
      originalConsole.warn.apply(console, arguments)
    }
    console.error = function () {
      forwardConsole("error", arguments)
      originalConsole.error.apply(console, arguments)
    }
    console.info = function () {
      forwardConsole("info", arguments)
      originalConsole.info.apply(console, arguments)
    }

    window.addEventListener("error", function (e) {
      forwardConsole("error", [e.message + " at " + (e.filename || "") + ":" + (e.lineno || "")])
    })

    window.addEventListener("unhandledrejection", function (e) {
      forwardConsole("error", ["Unhandled promise rejection: " + serializeArg(e.reason)])
    })

    // Highlight overlays
    var hoverOutline = document.createElement("div")
    hoverOutline.id = "__nikcli_hover_outline"
    hoverOutline.style.cssText =
      "position:fixed;pointer-events:none;border:2px solid #3b82f6;background:rgba(59,130,246,0.12);z-index:999999;display:none;border-radius:3px;transition:all 0.05s ease;"

    var hoverBadge = document.createElement("div")
    hoverBadge.id = "__nikcli_hover_badge"
    hoverBadge.style.cssText =
      "position:fixed;pointer-events:none;background:#2563eb;color:#ffffff;font-size:11px;font-weight:600;font-family:ui-sans-serif,system-ui,sans-serif;line-height:1;padding:4px 7px;border-radius:3px 3px 0 0;z-index:1000000;display:none;"

    var dropIndicator = document.createElement("div")
    dropIndicator.id = "__nikcli_drop_indicator"
    dropIndicator.style.cssText =
      "position:fixed;pointer-events:none;background:#10b981;z-index:999999;display:none;border-radius:2px;box-shadow:0 0 8px rgba(16,185,129,0.8);"

    // Elements the host has attached to the chat stay outlined so a multi-element
    // selection is visible while the user keeps clicking.
    var selectedEls = []
    var selectionLayer = document.createElement("div")
    selectionLayer.id = "__nikcli_selection_layer"
    selectionLayer.style.cssText = "position:fixed;inset:0;pointer-events:none;z-index:999998;display:block;"

    function renderSelection() {
      selectionLayer.innerHTML = ""
      for (var i = 0; i < selectedEls.length; i++) {
        var rect = selectedEls[i].getBoundingClientRect()
        var box = document.createElement("div")
        box.style.cssText =
          "position:fixed;pointer-events:none;border:2px solid #2563eb;background:rgba(37,99,235,0.10);border-radius:3px;top:" +
          rect.top +
          "px;left:" +
          rect.left +
          "px;width:" +
          rect.width +
          "px;height:" +
          rect.height +
          "px;"
        selectionLayer.appendChild(box)
      }
    }

    window.addEventListener("scroll", renderSelection, true)
    window.addEventListener("resize", renderSelection)

    function attachOverlays() {
      if (document.body && !document.getElementById("__nikcli_hover_outline")) {
        document.body.appendChild(hoverOutline)
        document.body.appendChild(hoverBadge)
        document.body.appendChild(dropIndicator)
        document.body.appendChild(selectionLayer)
      }
    }

    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", attachOverlays)
    } else {
      attachOverlays()
    }

    function detectLanguage() {
      var scripts = document.querySelectorAll("script")
      for (var i = 0; i < scripts.length; i++) {
        var src = scripts[i].src || ""
        if (src.indexOf(".tsx") !== -1 || src.indexOf("tsx") !== -1) return "tsx"
        if (src.indexOf(".jsx") !== -1 || src.indexOf("jsx") !== -1) return "jsx"
        if (src.indexOf(".vue") !== -1 || src.indexOf("vue") !== -1) return "vue"
        if (src.indexOf(".svelte") !== -1 || src.indexOf("svelte") !== -1) return "svelte"
      }
      return "tsx"
    }

    function getUniqueSelector(el) {
      if (!el || el.nodeType !== Node.ELEMENT_NODE) return ""
      if (el.id) return "#" + CSS.escape(el.id)

      var path = []
      while (el && el.nodeType === Node.ELEMENT_NODE) {
        if (el === document.body || el === document.documentElement) {
          path.unshift(el.nodeName.toLowerCase())
          break
        }
        var selector = el.nodeName.toLowerCase()
        if (el.id) {
          selector += "#" + CSS.escape(el.id)
          path.unshift(selector)
          break
        } else if (el.className && typeof el.className === "string") {
          var classes = el.className
            .trim()
            .split(/\s+/)
            .filter(function (c) {
              return c && !c.startsWith("__nikcli")
            })
          if (classes.length > 0) {
            selector += "." + CSS.escape(classes[0])
          }
        }

        var sib = el,
          nth = 1
        while ((sib = sib.previousElementSibling)) {
          if (sib.nodeName.toLowerCase() === el.nodeName.toLowerCase()) nth++
        }
        if (nth > 1) selector += ":nth-of-type(" + nth + ")"

        path.unshift(selector)
        el = el.parentElement
      }
      return path.join(" > ")
    }

    // Sections: what a person calls a part of a page, so "the hero" or "the
    // footer" can be picked and named without knowing the markup.
    var WORD_SECTIONS = {
      hero: "hero",
      jumbotron: "hero",
      masthead: "hero",
      splash: "hero",
      header: "header",
      topbar: "header",
      navbar: "nav",
      nav: "nav",
      navigation: "nav",
      menu: "nav",
      menubar: "nav",
      breadcrumb: "nav",
      breadcrumbs: "nav",
      footer: "footer",
      sidebar: "sidebar",
      drawer: "sidebar",
      banner: "banner",
      announcement: "banner",
      pricing: "pricing",
      plans: "pricing",
      features: "features",
      feature: "features",
      benefits: "features",
      testimonials: "testimonials",
      testimonial: "testimonials",
      reviews: "testimonials",
      faq: "faq",
      faqs: "faq",
      cta: "cta",
      contact: "contact",
      contacts: "contact",
      contatti: "contact",
      gallery: "gallery",
      team: "team",
      about: "about",
      services: "services",
      servizi: "services",
      newsletter: "newsletter",
      subscribe: "newsletter",
      blog: "blog",
      posts: "blog",
      products: "products",
      catalog: "products",
      catalogo: "products",
      prodotti: "products",
      cart: "cart",
      carrello: "cart",
      checkout: "checkout",
      search: "search",
      modal: "modal",
      dialog: "modal",
      stats: "stats",
      logos: "logos",
      partners: "logos",
      clients: "logos",
      steps: "steps",
      timeline: "timeline",
      portfolio: "portfolio",
      projects: "portfolio",
      login: "login",
      signin: "login",
      signup: "signup",
      register: "signup",
      card: "card",
      form: "form",
    }
    var ROLE_SECTIONS = {
      banner: "header",
      contentinfo: "footer",
      navigation: "nav",
      complementary: "sidebar",
      main: "main",
      search: "search",
      dialog: "modal",
      form: "form",
    }
    var TAG_SECTIONS = {
      header: "header",
      footer: "footer",
      nav: "nav",
      aside: "sidebar",
      main: "main",
      form: "form",
      dialog: "modal",
      section: "section",
      article: "article",
    }
    // Too big or too vague to be the answer while something closer has a name.
    var WEAK_SECTIONS = { main: true, section: true, article: true }

    function has(table, key) {
      return Object.prototype.hasOwnProperty.call(table, key)
    }

    function sectionWords(el) {
      var text = [
        el.id || "",
        typeof el.className === "string" ? el.className : "",
        el.getAttribute("aria-label") || "",
        el.getAttribute("data-testid") || "",
      ].join(" ")
      return text
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .toLowerCase()
        .split(/[^a-z0-9]+/)
    }

    function looksLikeHero(el) {
      var tag = el.tagName.toLowerCase()
      if (tag !== "section" && tag !== "div" && tag !== "header") return false
      if (!el.querySelector("h1")) return false
      var rect = el.getBoundingClientRect()
      var top = rect.top + (window.scrollY || 0)
      var vw = document.documentElement.clientWidth || 0
      var vh = document.documentElement.clientHeight || 0
      return vw > 0 && vh > 0 && top < vh && rect.width >= vw * 0.8 && rect.height >= vh * 0.3
    }

    function sectionNameOf(el) {
      if (!el || el.nodeType !== Node.ELEMENT_NODE || el === document.body || el === document.documentElement) return ""
      var given = (el.getAttribute("data-section") || "")
        .toLowerCase()
        .replace(/[^a-z0-9 -]+/g, "")
        .trim()
      if (given) return given.slice(0, 30)
      var words = sectionWords(el)
      for (var i = 0; i < words.length; i++) {
        if (has(WORD_SECTIONS, words[i])) return WORD_SECTIONS[words[i]]
      }
      var role = (el.getAttribute("role") || "").toLowerCase()
      if (has(ROLE_SECTIONS, role)) return ROLE_SECTIONS[role]
      if (looksLikeHero(el)) return "hero"
      var tag = el.tagName.toLowerCase()
      return has(TAG_SECTIONS, tag) ? TAG_SECTIONS[tag] : ""
    }

    function sectionLabel(el, name) {
      var heading = el.querySelector("h1, h2, h3")
      var text = heading ? (heading.textContent || "").replace(/\s+/g, " ").trim().slice(0, 40) : ""
      return text ? name + " «" + text + "»" : name
    }

    // The nearest section at or above el; a vague one only when nothing closer is named.
    function sectionOf(el) {
      var weak = null
      for (
        var node = el;
        node && node !== document.body && node !== document.documentElement;
        node = node.parentElement
      ) {
        var name = sectionNameOf(node)
        if (!name) continue
        if (!WEAK_SECTIONS[name]) return { el: node, name: name }
        if (!weak) weak = { el: node, name: name }
      }
      return weak
    }

    function getCleanOuterHTML(el) {
      if (!el) return ""
      var clone = el.cloneNode(false)
      var html = clone.outerHTML || ""
      if (html.length > 300) {
        html = html.slice(0, 300) + "..."
      }
      return html
    }

    function serializeElement(el) {
      if (!el || el === hoverOutline || el === hoverBadge || el === dropIndicator) return null
      var rect = el.getBoundingClientRect()
      var cs = window.getComputedStyle(el)
      var parent = el.parentElement
      var ownName = sectionNameOf(el)
      var around = sectionOf(parent)

      return {
        selector: getUniqueSelector(el),
        tagName: el.tagName.toLowerCase(),
        id: el.id || "",
        className: el.className ? (typeof el.className === "string" ? el.className : "") : "",
        innerText: (el.innerText || "").slice(0, 80).trim(),
        outerHTML: getCleanOuterHTML(el),
        detectedLanguage: detectLanguage(),
        rect: {
          top: rect.top,
          left: rect.left,
          width: Math.round(rect.width),
          height: Math.round(rect.height),
        },
        styles: {
          display: cs.display,
          flexDirection: cs.flexDirection,
          alignItems: cs.alignItems,
          justifyContent: cs.justifyContent,
          gap: cs.gap,
          padding: cs.padding,
          margin: cs.margin,
          color: cs.color,
          backgroundColor: cs.backgroundColor,
          fontSize: cs.fontSize,
          fontWeight: cs.fontWeight,
          lineHeight: cs.lineHeight,
          textAlign: cs.textAlign,
          borderRadius: cs.borderRadius,
          borderWidth: cs.borderWidth,
          borderColor: cs.borderColor,
          opacity: cs.opacity,
          boxShadow: cs.boxShadow,
          width: cs.width,
          height: cs.height,
        },
        parentSelector: parent ? getUniqueSelector(parent) : undefined,
        siblingsCount: parent ? parent.children.length : 0,
        indexInParent: parent ? Array.prototype.indexOf.call(parent.children, el) : 0,
        section: around
          ? { name: around.name, label: sectionLabel(around.el, around.name), selector: getUniqueSelector(around.el) }
          : undefined,
        ownSection: ownName ? sectionLabel(el, ownName) : undefined,
        textOnly: el.children.length === 0 && (el.textContent || "").trim().length > 0,
      }
    }

    function updateHoverOverlay(el) {
      attachOverlays()
      if (!el || currentMode !== "edit" || isDragging) {
        hoverOutline.style.display = "none"
        hoverBadge.style.display = "none"
        return
      }
      var rect = el.getBoundingClientRect()
      hoverOutline.style.display = "block"
      hoverOutline.style.top = rect.top + "px"
      hoverOutline.style.left = rect.left + "px"
      hoverOutline.style.width = rect.width + "px"
      hoverOutline.style.height = rect.height + "px"

      var ownName = sectionNameOf(el)
      var around = ownName ? null : sectionOf(el.parentElement)
      hoverBadge.textContent = ownName
        ? sectionLabel(el, ownName)
        : el.tagName.toLowerCase() + (around ? " · " + around.name : "")
      hoverBadge.style.display = "block"
      // Flush against the top-left corner of the outline, like a tab on it.
      hoverBadge.style.top = Math.max(0, rect.top - 19) + "px"
      hoverBadge.style.left = Math.max(0, rect.left) + "px"
    }

    // Mousemove highlight in Edit mode
    listenInput(
      document,
      "mousemove",
      function (e) {
        if (currentMode !== "edit") {
          hoverOutline.style.display = "none"
          hoverBadge.style.display = "none"
          return
        }
        if (isDragging) return
        var target = document.elementFromPoint(e.clientX, e.clientY)
        if (
          !target ||
          target === document.documentElement ||
          target === document.body ||
          target === hoverOutline ||
          target === hoverBadge ||
          target === dropIndicator
        ) {
          if (hoveredEl) {
            hoveredEl = null
            updateHoverOverlay(null)
          }
          return
        }
        if (target !== hoveredEl) {
          hoveredEl = target
          updateHoverOverlay(target)
        }
      },
      true,
    )

    // Mousedown to prepare drag & drop in Edit mode
    listenInput(
      document,
      "mousedown",
      function (e) {
        if (currentMode !== "edit") return
        var target = document.elementFromPoint(e.clientX, e.clientY)
        if (!target || target === document.body || target === document.documentElement) return
        draggedEl = target
        draggedEl.setAttribute("draggable", "true")
        isDragging = false
      },
      true,
    )

    // A plain click never fires dragend, so the attribute would otherwise stay on
    // the host page's element after the editor is closed.
    listenInput(
      document,
      "mouseup",
      function () {
        if (draggedEl && !isDragging) draggedEl.removeAttribute("draggable")
      },
      true,
    )

    listenInput(
      document,
      "dragstart",
      function (e) {
        if (currentMode !== "edit" || !draggedEl) return
        isDragging = true
        e.dataTransfer.setData("text/plain", getUniqueSelector(draggedEl))
        e.dataTransfer.effectAllowed = "move"
        draggedEl.style.opacity = "0.4"
        hoverOutline.style.display = "none"
        hoverBadge.style.display = "none"
      },
      true,
    )

    listenInput(
      document,
      "dragover",
      function (e) {
        if (currentMode !== "edit" || !draggedEl) return
        e.preventDefault()
        e.dataTransfer.dropEffect = "move"

        var target = document.elementFromPoint(e.clientX, e.clientY)
        if (!target || target === draggedEl || target === document.body || target === document.documentElement) {
          dropIndicator.style.display = "none"
          return
        }

        dropTargetEl = target
        var rect = target.getBoundingClientRect()
        var midY = rect.top + rect.height / 2

        dropIndicator.style.display = "block"
        dropIndicator.style.left = rect.left + "px"
        dropIndicator.style.width = rect.width + "px"
        dropIndicator.style.height = "3px"

        if (e.clientY < midY) {
          dropPosition = "before"
          dropIndicator.style.top = rect.top - 1 + "px"
        } else {
          dropPosition = "after"
          dropIndicator.style.top = rect.bottom - 1 + "px"
        }
      },
      true,
    )

    listenInput(
      document,
      "dragend",
      function (e) {
        if (draggedEl) {
          draggedEl.style.opacity = "1"
          draggedEl.removeAttribute("draggable")
        }
        dropIndicator.style.display = "none"
        setTimeout(function () {
          isDragging = false
        }, 50)
      },
      true,
    )

    listenInput(
      document,
      "drop",
      function (e) {
        if (currentMode !== "edit" || !draggedEl || !dropTargetEl) return
        e.preventDefault()
        e.stopPropagation()

        var parent = dropTargetEl.parentElement
        if (parent && draggedEl !== dropTargetEl) {
          var oldIndex = Array.prototype.indexOf.call(parent.children, draggedEl)
          if (dropPosition === "before") {
            parent.insertBefore(draggedEl, dropTargetEl)
          } else {
            parent.insertBefore(draggedEl, dropTargetEl.nextElementSibling)
          }
          var newIndex = Array.prototype.indexOf.call(parent.children, draggedEl)

          window.parent.postMessage(
            {
              type: "visual-editor:element-reordered",
              selector: getUniqueSelector(draggedEl),
              parentSelector: getUniqueSelector(parent),
              oldIndex: oldIndex,
              newIndex: newIndex,
              outerHTML: getCleanOuterHTML(draggedEl),
            },
            "*",
          )

          window.parent.postMessage({ type: "visual-editor:dom-changed" }, "*")
        }

        if (draggedEl) {
          draggedEl.style.opacity = "1"
          draggedEl.removeAttribute("draggable")
        }
        draggedEl = null
        dropTargetEl = null
        dropIndicator.style.display = "none"
        setTimeout(function () {
          isDragging = false
        }, 50)
      },
      true,
    )

    // Click handler (Select & Link on click if not dragging)
    listenInput(
      document,
      "click",
      function (e) {
        if (currentMode !== "edit") return
        if (isDragging) return // ignore click if user just dropped an element
        e.preventDefault()
        e.stopPropagation()

        var target = document.elementFromPoint(e.clientX, e.clientY)
        if (!target || target === hoverOutline || target === hoverBadge || target === dropIndicator) return
        // Alt+click: the whole section the element is in.
        if (e.altKey) {
          var whole = sectionOf(target)
          if (whole) target = whole.el
        }

        var serialized = serializeElement(target)
        if (serialized) {
          if (selectedEls.indexOf(target) === -1) selectedEls.push(target)
          renderSelection()
          window.parent.postMessage(
            {
              type: "visual-editor:element-selected",
              element: serialized,
            },
            "*",
          )
        }
        hoverOutline.style.display = "none"
        hoverBadge.style.display = "none"
      },
      true,
    )

    function query(selector) {
      try {
        return typeof selector === "string" ? document.querySelector(selector) : null
      } catch (err) {
        return null
      }
    }

    function reportEdit(selector, property, before, after) {
      window.parent.postMessage(
        {
          type: "visual-editor:edit-applied",
          selector: selector,
          property: property,
          before: String(before == null ? "" : before).slice(0, 500),
          after: String(after == null ? "" : after).slice(0, 500),
        },
        "*",
      )
    }

    // Message listener from parent host
    window.addEventListener("message", function (e) {
      if (!e.data || typeof e.data !== "object") return

      if (e.data.type === "visual-editor:set-mode") {
        currentMode = e.data.mode
        if (currentMode === "browse") {
          hoverOutline.style.display = "none"
          hoverBadge.style.display = "none"
          dropIndicator.style.display = "none"
        }
      } else if (e.data.type === "visual-editor:clear-selection") {
        // With a selectors list the host is pruning individual chips; without one
        // the whole selection is being dropped.
        if (Array.isArray(e.data.selectors)) {
          selectedEls = selectedEls.filter(function (el) {
            return e.data.selectors.indexOf(getUniqueSelector(el)) !== -1
          })
        } else {
          selectedEls = []
        }
        renderSelection()
      } else if (e.data.type === "visual-editor:apply-style") {
        var el = query(e.data.selector)
        if (el && typeof e.data.property === "string") {
          var before = window.getComputedStyle(el)[e.data.property]
          el.style[e.data.property] = e.data.value
          reportEdit(e.data.selector, e.data.property, before, window.getComputedStyle(el)[e.data.property])
          renderSelection()
        }
      } else if (e.data.type === "visual-editor:apply-text") {
        var textEl = query(e.data.selector)
        if (textEl && textEl.children.length === 0 && typeof e.data.text === "string") {
          var oldText = textEl.textContent || ""
          textEl.textContent = e.data.text
          reportEdit(e.data.selector, "text", oldText, e.data.text)
          renderSelection()
        }
      } else if (e.data.type === "visual-editor:select-section") {
        var inner = query(e.data.selector)
        var outer = inner ? sectionOf(inner.parentElement) : null
        if (outer) {
          if (selectedEls.indexOf(outer.el) === -1) selectedEls.push(outer.el)
          renderSelection()
          window.parent.postMessage(
            { type: "visual-editor:element-selected", element: serializeElement(outer.el) },
            "*",
          )
        }
      }
    })

    // Notify parent that bridge is ready
    window.parent.postMessage({ type: "visual-editor:ready" }, "*")
  })()
})
